TAB_HEADERS = {
    "meters": ["meter_id", "name", "location", "sort_order", "active", "default_rate"],
    "readings": [
        "reading_id",
        "batch_id",
        "date",
        "week",
        "line_source_id",
        "line_user_id",
        "meter_id",
        "current_value",
        "last_value",
        "produced_unit",
        "rate",
        "amount",
        "ocr_raw_text",
        "ocr_value",
        "confirmation_method",
        "image_message_id",
        "image_file_id",
        "created_at",
    ],
    "batches": [
        "batch_id",
        "week",
        "date",
        "line_source_id",
        "expected_meter_count",
        "confirmed_meter_count",
        "status",
        "report_image_url",
        "created_at",
        "updated_at",
    ],
    "pending_confirmations": [
        "confirmation_id",
        "line_source_id",
        "line_user_id",
        "meter_id",
        "batch_id",
        "image_message_id",
        "ocr_value",
        "ocr_raw_text",
        "status",
        "expires_at",
        "created_at",
    ],
    "settings": ["key", "value", "notes"],
    "audit_log": [
        "event_id",
        "timestamp",
        "event_type",
        "line_source_id",
        "meter_id",
        "payload_json",
    ],
}
